name:                Day-Eleven
version:             0.1.0.0
github:              "githubuser/Day-Eleven"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Day-Eleven#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- array >= 0.5 && < 0.6
- pretty-simple >= 2.2 && < 2.3 

library:
  source-dirs: src

executables:
  Day-Eleven-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day-Eleven

tests:
  Day-Eleven-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day-Eleven
